### ISSUE TITLE
Find use cases and queries

### ISSUE THREAD

**Issue by iprapas** [NebulaStream-Optimizer/ml-for-optimizer#1]
We should find use cases and queries to test the scaling of the operators

**Comment by spapadop** [comment]
1. Car stream (carId, carType, roadType, streetId, timestamp)
- Query 1: find intersections/streets with most cars, in order to predict upcoming traffic congestion
- Query 2: identify tracks on highways on illegal timeslots

2. Clickstream (websiteId, referrerSiteId, IPadress, timestamp, userAgent)
- Query 1: events counting (for identifying fradulent activity)
- Query 2: number of website visitors per country
